### ISSUE TITLE
DebugMenu while in game

### ISSUE THREAD

**Issue by MichaelGombos** [MichaelGombos/The-Art-Of-Drift#93]
This is needed before I can record a trailer

![Image](https://github.com/MichaelGombos/browser-driving-demo/assets/71684424/ac3c0217-e3a7-4f47-beac-4925cde2f030)

### Features:

**Camera menu**: (completed in ec8e4d02c3d4233ff2d0ce2bde6bfd7822effd2c)
zoom in/out
set fly speed
set x/y
set game speed (and rewind game)
set game time
enable free cam
pause game
**Teleport Menu**
Add teleport location based on current location
Add teleport location based on prompt
Teleport to location on location list
Delete location on location list
**Car Menu**
View each ghost car type
Teleport to any ghost car
Focus the camera on any ghost car
Change any ghost car vehicle body
Disable any ghost car

### Tasks:

- [ ] **Debug menu:**

- [x] **Debug menu base**

- [x] add debug menu toggle to settings
- [x] add debug menu base
- [x] add debug menu components + style

- [x] **Camera menu features**

- [x] add zoom function
- [x] add fly speed function
- [x] add setx/y function
- [x] add gamespeed function
- [x] add game time function
- [x] add free cam on/off function
- [x] add play/pause game function (need a flag to let the user move with placeCharacter if in devmode)
- [x] add seek to start function
- [x] add seek to end function
- [x] add toggle for car menu and teleport menu
- [x] disable sending run to database if opened

- [x] **Ghost car menu:**

- [x] Add toggle ghost car menu function
- [x] add base UI/component
- [x] add all components
- [x] update display to read car type on load
- [x] add teleport function
- [x] add focus camera function
- [x] add cycle car type function
- [x] add toggle car function

- [x] **Teleport menu:**

- [x] create example menu ui with filler teleport list
- [x] add tp to camera location function
- [x] add tp to prompt function
- [x] add ability to store locations in list with react and select them.
- [x] add function to delete location
- [x] save list to local storage
